# Generated by Django 5.0.7 on 2024-08-03 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfoModel',
            fields=[
                ('proposal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('profile', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WasteInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('type', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('proposal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_infos', to='info.companyinfomodel')),
            ],
        ),
    ]
